"""
Google AI Studio Grounded Prospector (src/scanner/ai_studio_prospector.py)

Uses Google AI Studio (Gemini 2.0 Flash) with Google Search Tool Grounding to:
1. Cross-reference prospective trading targets against live news, token unlocks, and social catalysts.
2. Veto tokens subject to active exploit rumors, delistings, or regulatory actions.
3. Boost conviction on verified spot accumulation and protocol catalysts.

Graceful Degradation:
- If GEMINI_API_KEY is not configured or rate-limited, safely returns original quantitative candidates.
"""

import sys
from pathlib import Path
REPO_ROOT = str(Path(__file__).resolve().parents[2])
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

import os
import json
import time
import argparse
from typing import Dict, Any, List, Optional

from src.utils.llm_client import UnifiedLLMClient

PROSPECTOR_PROMPT_TEMPLATE = """You are a senior quantitative crypto research analyst vetting perpetual trade candidates on Hyperliquid.
Below is a list of candidate trade setups generated by our quantitative scanners:

{candidates_json}

Your task:
Use Google Search grounding to verify whether any of these candidate tokens have TOXIC real-time catalysts in the last 24-48 hours:
- Active smart contract exploit or bridge hack
- Imminent massive token unlock (>5% circulating supply today)
- Exchange delisting or severe regulatory action
- Phishing / developer rug-pull rumors

For each candidate token, return an object in a JSON array:
[
  {{
    "coin": "COIN_SYMBOL",
    "validated": true/false (false if toxic catalyst found),
    "news_sentiment": "BULLISH" | "NEUTRAL" | "TOXIC_CATALYST",
    "adjusted_conviction": integer 0-100,
    "catalyst_verdict": "1 concise sentence summarizing news/unlock status",
    "citation": "source domain or headline if applicable"
  }}
]

Respond STRICTLY with a valid JSON array."""


class AIStudioProspector:
    """
    Macro & News-grounded prospector powered by Google AI Studio.
    """

    def __init__(
        self,
        llm_client: Optional[UnifiedLLMClient] = None,
        prospects_file: Optional[str] = None,
    ):
        self.llm_client = llm_client or UnifiedLLMClient()
        self.prospects_file = prospects_file or os.path.join(REPO_ROOT, "bridge", "prospects.json")

    def is_available(self) -> bool:
        """Check if AI Studio is configured and ready."""
        return self.llm_client.is_gemini_ready()

    def enhance_prospects(
        self,
        raw_prospects: List[Dict[str, Any]],
        use_search: bool = True,
    ) -> List[Dict[str, Any]]:
        """
        Enhance a list of raw prospect dicts with Google Search-grounded news sentiment and safety vetoes.
        """
        if not raw_prospects:
            return []

        if not self.is_available():
            # Graceful pass-through: return candidates unhindered
            return raw_prospects

        # Only analyze the top 6 candidates to conserve latency and token limits
        eval_candidates = raw_prospects[:6]
        compact_input = []
        for p in eval_candidates:
            compact_input.append({
                "coin": p.get("coin"),
                "bias": p.get("bias"),
                "base_conviction": p.get("conviction_score", p.get("score", 80)),
                "strategy": p.get("strategy"),
                "funding_apr": p.get("funding_apr_pct", p.get("funding_apr", 0.0)),
                "change_24h": p.get("change_24h", 0.0),
                "volume_24h_usd": p.get("volume_24h_usd", p.get("volume_24h", 0.0)),
            })

        prompt = PROSPECTOR_PROMPT_TEMPLATE.format(candidates_json=json.dumps(compact_input, indent=2))

        try:
            grounded_results = self.llm_client.query_gemini_json(
                prompt=prompt,
                model="gemini-3-flash-preview",
                use_search=use_search,
                temperature=0.2,
                retries=2,
            )

            if not grounded_results or not isinstance(grounded_results, list):
                return raw_prospects

            # Index grounded responses by coin symbol
            verdicts = {}
            for item in grounded_results:
                if isinstance(item, dict) and "coin" in item:
                    c = str(item["coin"]).upper()
                    verdicts[c] = item

            # Merge verdicts into candidates
            enhanced = []
            for p in raw_prospects:
                coin = p.get("coin", "").upper()
                v = verdicts.get(coin)
                p_copy = dict(p)

                if v:
                    p_copy["ai_studio_validated"] = v.get("validated", True)
                    p_copy["news_sentiment"] = v.get("news_sentiment", "NEUTRAL")
                    p_copy["catalyst_verdict"] = v.get("catalyst_verdict", "No toxic catalysts detected.")
                    p_copy["news_citation"] = v.get("citation", "")

                    # Adjust conviction score based on news grounding
                    base_score = float(p.get("conviction_score", p.get("score", 80)))
                    ai_score = float(v.get("adjusted_conviction", base_score))

                    if v.get("news_sentiment") == "TOXIC_CATALYST" or not v.get("validated", True):
                        p_copy["conviction_score"] = min(base_score, 40)
                        p_copy["score"] = min(base_score, 40)
                        p_copy["rationale"] = f"⚠️ [AI Studio VETO] {v.get('catalyst_verdict')} | {p.get('rationale', '')}"
                    elif v.get("news_sentiment") == "BULLISH":
                        boosted = min(98, max(base_score, ai_score + 5))
                        p_copy["conviction_score"] = boosted
                        p_copy["score"] = boosted
                        p_copy["rationale"] = f"🌟 [AI Studio Verified] {v.get('catalyst_verdict')} | {p.get('rationale', '')}"
                    else:
                        p_copy["conviction_score"] = ai_score
                        p_copy["score"] = ai_score
                else:
                    p_copy["ai_studio_validated"] = True
                    p_copy["news_sentiment"] = "NEUTRAL"
                    p_copy["catalyst_verdict"] = "Standard quantitative setup."

                enhanced.append(p_copy)

            # Re-sort by final conviction score (highest first)
            enhanced.sort(key=lambda x: x.get("conviction_score", x.get("score", 0)), reverse=True)
            return enhanced

        except Exception as e:
            print(f"[AI Studio Prospector] Notice: {e}")
            return raw_prospects

    def process_file(self, dry_run: bool = False) -> List[Dict[str, Any]]:
        """Read bridge/prospects.json, enhance with AI Studio, and write back."""
        if not os.path.exists(self.prospects_file):
            print(f"Prospects file not found at: {self.prospects_file}")
            return []

        try:
            with open(self.prospects_file, "r") as f:
                data = json.load(f)

            prospects_list = data.get("prospects", []) if isinstance(data, dict) else (data if isinstance(data, list) else [])
            if not prospects_list:
                print("No prospects found in file.")
                return []

            print(f"🔍 [AI Studio Prospector] Enhancing {len(prospects_list)} prospects with Google Search grounding...")
            enhanced = self.enhance_prospects(prospects_list, use_search=True)

            if not dry_run and isinstance(data, dict):
                data["prospects"] = enhanced
                data["ai_studio_enhanced_at"] = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
                tmp_path = f"{self.prospects_file}.tmp"
                with open(tmp_path, "w") as f:
                    json.dump(data, f, indent=2)
                os.replace(tmp_path, self.prospects_file)
                print(f"✅ Successfully updated {self.prospects_file} with AI Studio conviction adjustments.")

            return enhanced
        except Exception as e:
            print(f"Error processing prospects file: {e}")
            return []


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Google AI Studio Grounded Prospector for Hyperliquid")
    parser.add_argument("--file", type=str, default=None, help="Path to bridge/prospects.json")
    parser.add_argument("--dry-run", action="store_true", help="Print output without overwriting file")
    args = parser.parse_args()

    prospector = AIStudioProspector(prospects_file=args.file)
    results = prospector.process_file(dry_run=args.dry_run)
    for p in results[:5]:
        print(f"  • {p.get('coin')}: Score={p.get('conviction_score')} | Sentiment={p.get('news_sentiment')} | {p.get('catalyst_verdict', '')[:70]}")
