import re

with open("src/scanner/mcp_client.py", "r") as f:
    code = f.read()

old_func = '''    def get_meta_and_asset_ctxs(self) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
        """Fetch universe definitions and real-time asset contexts from local cache generated by MCP tools."""
        import json
        with open("catalog/mcp_meta_cache.json", "r") as f:
            data = json.load(f)
        resp = data.get("response", data) # Handle both MCP wrap and direct response
        return resp[0], resp[1]'''

new_func = '''    def get_meta_and_asset_ctxs(self) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
        """Fetch universe definitions and real-time asset contexts with a 5-second in-memory cache."""
        import time
        if not hasattr(self, "_cached_meta_ctx"):
            self._cached_meta_ctx = None
            self._cached_meta_ctx_time = 0
            
        if time.monotonic() - self._cached_meta_ctx_time < 5.0 and self._cached_meta_ctx:
            return self._cached_meta_ctx[0], self._cached_meta_ctx[1]
            
        try:
            resp = self._session.post(self.api_url, json={"type": "metaAndAssetCtxs"})
            if resp.status_code == 200:
                data = resp.json()
                self._cached_meta_ctx = (data[0], data[1])
                self._cached_meta_ctx_time = time.monotonic()
                return data[0], data[1]
        except Exception:
            pass
            
        # Fallback to local cache if network fails
        import json
        with open("catalog/mcp_meta_cache.json", "r") as f:
            data = json.load(f)
        resp = data.get("response", data)
        return resp[0], resp[1]'''

code = code.replace(old_func, new_func)

with open("src/scanner/mcp_client.py", "w") as f:
    f.write(code)

print("patched mcp_client.py!")
