with open("src/scanner/mcp_client.py", "r") as f:
    code = f.read()

old_post_ctxs = """    def get_meta_and_asset_ctxs(self) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
        \"\"\"Fetch universe definitions and real-time asset contexts from local cache generated by MCP tools.\"\"\"
        import json
        with open("catalog/mcp_meta_cache.json", "r") as f:
            data = json.load(f)
        return data[0], data[1]"""

new_post_ctxs = """    def get_meta_and_asset_ctxs(self) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
        \"\"\"Fetch universe definitions and real-time asset contexts from local cache generated by MCP tools.\"\"\"
        import json
        with open("catalog/mcp_meta_cache.json", "r") as f:
            data = json.load(f)
        resp = data.get("response", data) # Handle both MCP wrap and direct response
        return resp[0], resp[1]"""

code = code.replace(old_post_ctxs, new_post_ctxs)

with open("src/scanner/mcp_client.py", "w") as f:
    f.write(code)

print("patched mcp_client.py!")
